name: PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check:
    secrets: inherit
    uses: VerticeOne/github-reusable-workflows/.github/workflows/pull-request-title-checker.yaml@pr-check-stable
