---
name: Renovate repo dependencies
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options: [INFO, DEBUG]
        default: 'INFO'
jobs:
  renovate:
    runs-on: ["self-hosted", "graviton", "small"]
    steps:
      - uses: actions/checkout@v4

      - name: Run self-hosted Renovate bot
        uses: renovatebot/github-action@v41.0.14
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.VERTICE_PAT }}
        env:
          LOG_LEVEL: ${{ inputs.log-level }}
          RENOVATE_CONFIG: '{"repositories": ["${{ github.repository }}"]}'
